### PR TITLE
Pre-plan meal

### LINKED ISSUE #11: PRIO. 4 User Story: As a college student, I want to have pre-planned meals for the week, so I can save time on choosing what to eat.
Estimated 4-5 hours

### PR DESCRIPTION
**Pull request by gitstopher**

### CODE REVIEW

**Comment by gitstopher** [comment]
The pull isn't finished might have to change the classes of lunch, breakfast, and dinner as it isn't in the api

**Comment by gitstopher** [comment]
Got the API mostly set however for the preplan it fails to print out the food for the week still saying 502 error code

**Review by gitstopher — COMMENTED** [review]
has data saved

**Review by abg287 — APPROVED** [review]
Looks good

**Pull request merged**
